/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package GUI;

import entidades.EvaluacionesCalificadas;
import javax.swing.JComponent;
import javax.swing.JOptionPane;

/**
 *
 * @author renzo
 */
public class JDAgregarEvaluacion extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JDAgregarEvaluacion.class.getName());
    private EvaluacionesCalificadas evaluacion;

    /**
     * Creates new form JDAgregarEvaluacion
     */
    public JDAgregarEvaluacion(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNombreEvaluacion = new javax.swing.JLabel();
        txtNombreDeEvaluacion = new javax.swing.JTextField();
        lblSiglas = new javax.swing.JLabel();
        txtSiglas = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        spPeso = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        txtCronograma = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        lblNombreEvaluacion.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblNombreEvaluacion.setText("Nombre de Evaluacion:");

        txtNombreDeEvaluacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombreDeEvaluacionKeyReleased(evt);
            }
        });

        lblSiglas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lblSiglas.setText("Siglas");

        txtSiglas.setEditable(false);
        txtSiglas.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Peso");

        spPeso.setModel(new javax.swing.SpinnerNumberModel(5.0d, 5.0d, 100.0d, 5.0d));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Cronograma");

        btnAceptar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(lblSiglas)
                    .addComponent(lblNombreEvaluacion))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombreDeEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(spPeso, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                        .addComponent(txtSiglas, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(txtCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAceptar)
                .addGap(18, 18, 18)
                .addComponent(btnCancelar)
                .addGap(13, 13, 13))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreEvaluacion)
                    .addComponent(txtNombreDeEvaluacion, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSiglas)
                    .addComponent(txtSiglas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(spPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtCronograma, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAceptar)
                    .addComponent(btnCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed
        EvaluacionesCalificadas evaluacion;
        if (this.validardatos() == true) {
            this.evaluacion = this.crearEvaluacion();
            this.setVisible(false);
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtNombreDeEvaluacionKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombreDeEvaluacionKeyReleased
        String entrada = txtNombreDeEvaluacion.getText().trim();
    
    if (!entrada.isEmpty()) {
        String[] partes = entrada.split("\\s+");
        StringBuilder siglas = new StringBuilder();

        // Tomar primeras letras de palabras que no sean números
        for (String parte : partes) {
            if (!parte.matches("\\d+")) {
                siglas.append(parte.charAt(0));
            }
        }

        // Buscar si hay un número en la entrada
        String numero = "";
        for (String parte : partes) {
            if (parte.matches("\\d+")) {
                numero = parte;
                break;
            }
        }

        txtSiglas.setText(siglas.toString().toUpperCase() + numero);
    } else {
        txtSiglas.setText("");
    }

    }//GEN-LAST:event_txtNombreDeEvaluacionKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                JDAgregarEvaluacion dialog = new JDAgregarEvaluacion(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblNombreEvaluacion;
    private javax.swing.JLabel lblSiglas;
    private javax.swing.JSpinner spPeso;
    private javax.swing.JTextField txtCronograma;
    private javax.swing.JTextField txtNombreDeEvaluacion;
    private javax.swing.JTextField txtSiglas;
    // End of variables declaration//GEN-END:variables

    private boolean validardatos() {
        String mensaje="";
        JComponent componente = null;
        String valor;
        
        valor=this.txtNombreDeEvaluacion.getText();
        if (valor.isEmpty()|| valor.isBlank()) {
            mensaje+="Debe Llenar el campo de Nombre de la evaluacion";
            componente=this.txtNombreDeEvaluacion;
        }
        valor=this.txtCronograma.getText() ;
        if (valor.isEmpty()|| valor.isBlank()) {
            mensaje+="\n Debe llenar el campo de Cronograma";
        }
        
        if (componente!=null) {
            JOptionPane.showMessageDialog(this, mensaje);
            return false;
        }
        return true;
    }
    
    


    private EvaluacionesCalificadas crearEvaluacion() {
        EvaluacionesCalificadas eval= new EvaluacionesCalificadas();
        
        eval.setNombreEvaluacion(this.txtNombreDeEvaluacion.getText());
        eval.setSiglasEvaluacion(this.txtSiglas.getText());
        eval.setPeso((double) this.spPeso.getValue());
        eval.setCronograma(this.txtCronograma.getText());
        
        return eval;
    }

   public  EvaluacionesCalificadas agregar() {
       return this.evaluacion;
    }
    
    public void cargarDatos(EvaluacionesCalificadas evaluacion) {
    this.txtNombreDeEvaluacion.setText(evaluacion.getNombreEvaluacion());
    this.txtSiglas.setText(evaluacion.getSiglasEvaluacion());
    this.spPeso.setValue(evaluacion.getPeso());
    this.txtCronograma.setText(evaluacion.getCronograma());
    this.setVisible(true);
}
}
