
package GUI;

import GUI.modelos.InicioTableModel;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import entidades.Usuario;
import entidades.Docente;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author gutie
 */
public class JICuenta extends javax.swing.JInternalFrame {

    private static boolean estadoCambio = false;

    public static JICuenta frm = null;
    private InicioTableModel modelo = new InicioTableModel();
    private Usuario usuarioActual;

    public JICuenta() {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        setBorder(null);

        // Configurar listener para limpiar referencia cuando se cierre
        this.setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
        this.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent e) {
                frm = null;
            }
        });
    }

    public JICuenta(Usuario usuario) {
        initComponents();
        BasicInternalFrameUI ui = (BasicInternalFrameUI) this.getUI();
        ui.setNorthPane(null);
        setBorder(null);
        this.usuarioActual = usuario;
        cargarDatosUsuario();

        // Configurar listener para limpiar referencia cuando se cierre
        this.setDefaultCloseOperation(javax.swing.JInternalFrame.DISPOSE_ON_CLOSE);
        this.addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent e) {
                frm = null;
            }
        });
    }

    public static JICuenta crear(javax.swing.JDesktopPane contenedor, Usuario usuario) {

        if (JICuenta.frm == null) {
            JICuenta.frm = new JICuenta(usuario);
            JICuenta.frm.setResizable(true);
            contenedor.add(JICuenta.frm);
        } else {
            // Si ya existe la ventana, actualizar con el nuevo usuario
            JICuenta.frm.usuarioActual = usuario;
            JICuenta.frm.cargarDatosUsuario();
        }

        return JICuenta.frm;
    }

    public static JICuenta crear(javax.swing.JDesktopPane contenedor) {

        if (JICuenta.frm == null) {
            JICuenta.frm = new JICuenta();
            JICuenta.frm.setResizable(true);
            contenedor.add(JICuenta.frm);
        }

        return JICuenta.frm;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panInfUser = new javax.swing.JPanel();
        lblInfUser = new javax.swing.JLabel();
        lblDni = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        separadorUsuario1 = new javax.swing.JSeparator();
        lblNombres = new javax.swing.JLabel();
        txtNombres = new javax.swing.JTextField();
        separadorUsuario2 = new javax.swing.JSeparator();
        lblGrado1 = new javax.swing.JLabel();
        txtGrado1 = new javax.swing.JTextField();
        separadorUsuario3 = new javax.swing.JSeparator();
        lblCorreo1 = new javax.swing.JLabel();
        separadorUsuario4 = new javax.swing.JSeparator();
        btnModificar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        txtCorreo = new javax.swing.JTextField();
        btnCerrarSesion1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        lblInfProduct = new javax.swing.JLabel();
        lblEpiciCorp = new javax.swing.JLabel();

        setResizable(true);
        setPreferredSize(new java.awt.Dimension(1660, 1027));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        panInfUser.setBackground(new java.awt.Color(255, 255, 255));

        lblInfUser.setBackground(new java.awt.Color(255, 255, 255));
        lblInfUser.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInfUser.setText("Informacion de usuario");

        lblDni.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblDni.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblDni.setText("DNI");

        txtDni.setEditable(false);
        txtDni.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtDni.setBorder(null);
        txtDni.setCaretColor(new java.awt.Color(255, 255, 255));
        txtDni.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtDni.setFocusable(false);
        txtDni.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtDni.setSelectionColor(new java.awt.Color(232, 201, 42));
        txtDni.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDniKeyReleased(evt);
            }
        });

        separadorUsuario1.setBorder(new javax.swing.border.MatteBorder(null));

        lblNombres.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblNombres.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblNombres.setText("NOMBRES COMPLETOS");

        txtNombres.setEditable(false);
        txtNombres.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtNombres.setBorder(null);
        txtNombres.setCaretColor(new java.awt.Color(255, 255, 255));
        txtNombres.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtNombres.setFocusable(false);
        txtNombres.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtNombres.setSelectionColor(new java.awt.Color(232, 201, 42));
        txtNombres.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNombresKeyReleased(evt);
            }
        });

        separadorUsuario2.setBorder(new javax.swing.border.MatteBorder(null));

        lblGrado1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblGrado1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblGrado1.setText("GRADO ACADEMICO");

        txtGrado1.setEditable(false);
        txtGrado1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtGrado1.setBorder(null);
        txtGrado1.setCaretColor(new java.awt.Color(255, 255, 255));
        txtGrado1.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        txtGrado1.setFocusable(false);
        txtGrado1.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        txtGrado1.setSelectionColor(new java.awt.Color(232, 201, 42));
        txtGrado1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtGrado1KeyReleased(evt);
            }
        });

        separadorUsuario3.setBorder(new javax.swing.border.MatteBorder(null));

        lblCorreo1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        lblCorreo1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblCorreo1.setText("CORREO INSTITUCIONAL");

        separadorUsuario4.setBorder(new javax.swing.border.MatteBorder(null));

        btnModificar.setText("Modificar");

        jButton1.setText("Guardar Cambios");

        javax.swing.GroupLayout panInfUserLayout = new javax.swing.GroupLayout(panInfUser);
        panInfUser.setLayout(panInfUserLayout);
        panInfUserLayout.setHorizontalGroup(
            panInfUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfUserLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panInfUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panInfUserLayout.createSequentialGroup()
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addGap(25, 25, 25))
                    .addGroup(panInfUserLayout.createSequentialGroup()
                        .addGroup(panInfUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblGrado1)
                            .addComponent(lblNombres)
                            .addComponent(lblDni, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblInfUser)
                            .addComponent(txtDni, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(txtNombres)
                            .addComponent(txtGrado1)
                            .addComponent(separadorUsuario3)
                            .addComponent(separadorUsuario4)
                            .addComponent(separadorUsuario2)
                            .addComponent(separadorUsuario1)
                            .addComponent(lblCorreo1)
                            .addComponent(txtCorreo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panInfUserLayout.setVerticalGroup(
            panInfUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panInfUserLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblInfUser)
                .addGap(26, 26, 26)
                .addComponent(lblDni)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorUsuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNombres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorUsuario2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGrado1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrado1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorUsuario3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblCorreo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(separadorUsuario4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(panInfUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnCerrarSesion1.setBackground(new java.awt.Color(25, 118, 210));
        btnCerrarSesion1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnCerrarSesion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_endSesion.png"))); // NOI18N
        btnCerrarSesion1.setText(" CERRAR SESION");
        btnCerrarSesion1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 10, 1, 1, new java.awt.Color(0, 0, 0)));
        btnCerrarSesion1.setBorderPainted(false);
        btnCerrarSesion1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnCerrarSesion1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCerrarSesion1.setIconTextGap(5);
        btnCerrarSesion1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarSesion1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        lblInfProduct.setBackground(new java.awt.Color(255, 255, 255));
        lblInfProduct.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblInfProduct.setText("Informacion de producto");

        lblEpiciCorp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img_epici_corp.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnCerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1436, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panInfUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInfProduct)
                            .addComponent(lblEpiciCorp))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblInfProduct)
                        .addGap(30, 30, 30)
                        .addComponent(lblEpiciCorp, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 670, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(panInfUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(15, 15, 15)))
                .addComponent(btnCerrarSesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(71, 71, 71))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDniKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDniKeyReleased

    }//GEN-LAST:event_txtDniKeyReleased

    private void txtNombresKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombresKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombresKeyReleased

    private void txtGrado1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtGrado1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGrado1KeyReleased

    private void btnCerrarSesion1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarSesion1ActionPerformed
        java.awt.Window window = javax.swing.SwingUtilities.getWindowAncestor(this);
        if (window != null) {
            window.dispose();
        }
        frm = null;
        JFLogeo login = new JFLogeo();
        login.setVisible(true);
    }//GEN-LAST:event_btnCerrarSesion1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarSesion1;
    private javax.swing.JTextField btnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCorreo1;
    private javax.swing.JLabel lblDni;
    private javax.swing.JLabel lblEpiciCorp;
    private javax.swing.JLabel lblGrado1;
    private javax.swing.JLabel lblInfProduct;
    private javax.swing.JLabel lblInfUser;
    private javax.swing.JLabel lblNombres;
    private javax.swing.JPanel panInfUser;
    private javax.swing.JSeparator separadorUsuario1;
    private javax.swing.JSeparator separadorUsuario2;
    private javax.swing.JSeparator separadorUsuario3;
    private javax.swing.JSeparator separadorUsuario4;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtGrado1;
    private javax.swing.JTextField txtNombres;
    // End of variables declaration//GEN-END:variables

    private void cargarDatosUsuario() {
        if (usuarioActual != null && usuarioActual.getDocente() != null) {
            Docente docente = usuarioActual.getDocente();

            // Cargar datos en los campos de texto
            txtDni.setText(docente.getDni());
            txtNombres.setText(docente.getNombres() + " " + docente.getApellidos());
            txtGrado1.setText(docente.getGrado());
            txtCorreo.setText(docente.getCorreo());
        }
    }
}
